jobs:
  include:
    - dist: focal
      env:
        - TARGET_ENV=stage_focal
        - COMPARE_WITH=dev_focal
    - dist: focal
      env:
        - TARGET_ENV=dev_focal
        - COMPARE_WITH=stage_focal

script:
  - |
    set -euo pipefail
    export LC_ALL=C

    THIS_DIST=$(echo "$TARGET_ENV" | cut -d'_' -f2)
    mkdir -p "$THIS_DIST"

    dpkg-query -W -f='${Package} ${Version}\n' \
      > "$THIS_DIST/${TARGET_ENV}_installed_packages.txt"

after_success:
  - |
    set -euo pipefail
    export LC_ALL=C

    git config --global user.name  "kamildevtactics"
    git config --global user.email "kamil.maludzinski@devtactics.net"

    git clone https://kamildevtactics:$GITHUB_TOKEN@github.com/kamildevtactics/travis_build_test.git
    cd travis_build_test

    git pull --rebase origin main || git merge --ff-only origin/main

    THIS_DIST=$(echo "$TARGET_ENV" | cut -d'_' -f2)
    mkdir -p "$THIS_DIST"
    cp "../${THIS_DIST}/${TARGET_ENV}_installed_packages.txt" "$THIS_DIST/"

    git add "$THIS_DIST/${TARGET_ENV}_installed_packages.txt"
    git commit -m "Update installed packages ($TARGET_ENV)"
    git push origin main

    if [[ -n "$COMPARE_WITH" && -f "../${THIS_DIST}/${COMPARE_WITH}_installed_packages.txt" ]]; then
      echo "Generating diff report: $TARGET_ENV vs $COMPARE_WITH"
      TMPDIR=$(mktemp -d)
      cut -d' ' -f1 "${THIS_DIST}/${TARGET_ENV}_installed_packages.txt"  | sort > "$TMPDIR/${TARGET_ENV}_names.txt"
      cut -d' ' -f1 "${THIS_DIST}/${COMPARE_WITH}_installed_packages.txt" | sort > "$TMPDIR/${COMPARE_WITH}_names.txt"

      comm -23 "$TMPDIR/${COMPARE_WITH}_names.txt" "$TMPDIR/${TARGET_ENV}_names.txt" > "$TMPDIR/added.txt"
      comm -13 "$TMPDIR/${COMPARE_WITH}_names.txt" "$TMPDIR/${TARGET_ENV}_names.txt" > "$TMPDIR/removed.txt"
      comm -12 "$TMPDIR/${COMPARE_WITH}_names.txt" "$TMPDIR/${TARGET_ENV}_names.txt" > "$TMPDIR/common.txt"

      REPORT="${THIS_DIST}/${TARGET_ENV}_vs_${COMPARE_WITH}_diff.txt"
      {
        echo "====== PACKAGE COMPARISON: $TARGET_ENV vs $COMPARE_WITH ======"
        echo
        echo "1) ADDED:"
        echo "----------"
        if [[ -s "$TMPDIR/added.txt" ]]; then
          while read -r pkg; do
            ver=$(grep -m1 "^$pkg " "${THIS_DIST}/${COMPARE_WITH}_installed_packages.txt" | awk '{print $2}')
            echo "  + $pkg (version $ver)"
          done < "$TMPDIR/added.txt"
        else
          echo "  (none)"
        fi

        echo
        echo "2) REMOVED:"
        echo "------------"
        if [[ -s "$TMPDIR/removed.txt" ]]; then
          while read -r pkg; do
            ver=$(grep -m1 "^$pkg " "${THIS_DIST}/${TARGET_ENV}_installed_packages.txt" | awk '{print $2}')
            echo "  - $pkg (version $ver)"
          done < "$TMPDIR/removed.txt"
        else
          echo "  (none)"
        fi

        echo
        echo "3) VERSION CHANGES:"
        echo "---------------------"
        if [[ -s "$TMPDIR/common.txt" ]]; then
          while read -r pkg; do
            tv=$(grep -m1 "^$pkg " "${THIS_DIST}/${TARGET_ENV}_installed_packages.txt" | awk '{print $2}')
            cv=$(grep -m1 "^$pkg " "${THIS_DIST}/${COMPARE_WITH}_installed_packages.txt" | awk '{print $2}')
            if [[ "$tv" != "$cv" ]]; then
              echo "  * $pkg: $tv → $cv"
            fi
          done < "$TMPDIR/common.txt"
        else
          echo "  (none)"
        fi
      } > "$REPORT"

      rm -rf "$TMPDIR"
      git add "$REPORT"
      git commit -m "Add diff report for $TARGET_ENV vs $COMPARE_WITH"
      git push origin main
    else
      echo "No comparison available for $COMPARE_WITH; skipping diff."
    fi
